#ifndef DEBUG_DEFINITIONS_H
#define DEBUG_DEFINITIONS_H

//#define WORST_CASE_TIMING_TESTING
//#define PRINT_TIMING

#define ALLOW_KEY_MEASUREMENT_THREAD
#define ALLOW_DISPLAY_THREAD
#define ALLOW_KNOB_ACTION_THREAD
#define ALLOW_MY_PRINT_THREAD
#define ALLOW_CAN_RX_THREAD
#define ALLOW_CAN_TX_THREAD
#define ALLOW_SAMPLE_ISR

#endif